### ISSUE TITLE
No presence appears on Discord

### ISSUE THREAD

**Issue by DvidPiDev** [leonardssh/vscord#225]
Hey!
I just installed the plugin and restarted VSCode to no avail. Here are the logs: https://pastebin.com/8dUzpjW9
I'm running ZorinOS 16.2 (ZorinOS is based of Ubuntu)

Thanks in advance.

EDIT: This was caused by using flatpak/snap version of VSCode

**Comment by xhayper** [comment]
47e554b18c4c311ac938be0076c08f6241cf3e63 should fix this

**Comment by xhayper** [comment]
If it still doesn't work, please answer this question

Discord version: (PTB/Stable/Canary) (Version)
Flatpak/Snap/Normal:

**Comment by DvidPiDev** [comment]
Issue persists after update to v5.1.13

Discord Stable 213510 (8831bfd) Host 0.0.28 Linux 64-Bit (5.15.0-76-Generic)
Normal (.deb)

**Comment by xhayper** [comment]
I can't really boot up a VM now, i will look into this tomorrow

**Comment by xhayper** [comment]
Oh, and, can you run
```
ls $XDG_RUNTIME_DIR
```
? and tell me if you are using Wayland or X

**Comment by DvidPiDev** [comment]
![image](https://github.com/leonardssh/vscord/assets/79283415/7b5d314e-238c-4f66-967e-b05886ced4b8)
I'm using X.

**Comment by xhayper** [comment]
Alright, i think we can rule out that it is caused by the VSCord itself and not the discord-rpc lib itself

**Comment by xhayper** [comment]
can you send me then new error log that you got after updating to the latest version?

**Comment by DvidPiDev** [comment]
```
[4:34:53 PM] [ERROR] Encountered following error while trying to login: RPC_COULD_NOT_CONNECT: Could not connect
    at /home/david/.var/app/com.visualstudio.code/data/vscode/extensions/leonardssh.vscord-5.1.13/node_modules/.pnpm/@xhayper+discord-rpc@1.0.20/node_modules/@xhayper/discord-rpc/dist/transport/IPC.js:111:20
[4:34:53 PM] [INFO] [002] Destroyed Discord RPC client
[4:34:53 PM] [INFO] Successfully logged in to Discord with client ID 782685898163617802
[4:34:53 PM] [INFO] Discord Rich Presence for VS Code activated.
[4:34:53 PM] [INFO] Registered Discord Rich Presence commands
```

**Comment by xhayper** [comment]
ahh, could not connect but connect in the next moment, i have seen this before but don't understand why it would fail

**Comment by DvidPiDev** [comment]
I have no idea either :shrug: 
Other "Discord Presence" apps (not extensions in vscode) can connect to Discord just fine.

**Comment by xhayper** [comment]
Do you know how to setup a development version of vscord? i think it would be best if we try to debug it together, since this bug is very hard to replicate

**Comment by DvidPiDev** [comment]
Sorry, but I don't know how to do that.
I can also try spinning up a VM with the same OS and versions to see if it's just something on my machine.

**Comment by xhayper** [comment]
Sure, you can do that, if possible, join the discord, i might be able to guide you on how to set up a dev environment for the extension

**Comment by xhayper** [comment]
This was caused by using flatpak/snap version of VSCode
