### ISSUE TITLE
VSCord Activity Image Are Not Showed Up

### ISSUE THREAD

**Issue by YoruAkio** [leonardssh/vscord#381]
I don't know why my extension was correct, and i try to reinstall it its still not showing the image on the activity both for status and lang image

![Image](https://github.com/user-attachments/assets/5c36c922-fbc8-4686-9906-6755cf9e7d9c)

**Comment by YoruAkio** [comment]
Fixed!

Im using custom client ( legcord ), and if i using the official Discord client is working properly!

**Comment by NarwhalKid** [comment]
I mean this is still an issue right? VSCord activity images won't show up on custom clients. I'm using Vencord and have the same problem, but I don't if I use https://open-vsx.org/vscode/item?itemName=LeonardSSH.vscord

**Comment by nick22985** [comment]
Thats odd. It just uses url's as the image paths so it should load. Unless vencord is blocking certain requests to urls?
